name: Discord Notifier
on:
  push:
    branches: [ v10.x ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: fateyan/action-discord-notifier@v1
        with:
          message-title: New Commits to [Module-Iqreable]
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
